import "./globals.css";

export const metadata = {
  title: "Bubatag",
  description: "Generated by create next app",
  // Adicionamos a propriedade icons aqui para definir o favicon
  icons: {
    icon: "/imgs/simbolo.svg", 
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}